export const ARTICLE_ACTIONS = {
  ARTICLE_FETCH_ARTICLES: {
    LOADING: "ARTICLE_FETCH_ARTICLES_LOADING",
    SUCCESS: "ARTICLE_FETCH_ARTICLES_SUCCESS",
    FAIL: "ARTICLE_FETCH_ARTICLES_FAIL",
  },
};
