export const MODAL_ACTIONS = {
  UPDATE_MODAL_STATE: "UPDATE_MODAL_STATE",
  CLOSE_MODAL: "CLOSE_MODAL",
};

export const MODAL_TYPES = {
  FEATHER_LIGHT: "FEATHER_LIGHT",
  SECURE_TRANSACTION: "SECURE_TRANSACTION",
  LOGIN: "LOGIN",
  BRAND: "BRAND",
};
