export const NAVBAR_ACTIONS = {
  UPDATE_IS_OPEN: "UPDATE_IS_OPEN",
  UPDATE_CUSTOM_NAV_INFO: "UPDATE_CUSTOM_NAV_INFO",
};

export const OPENED_TYPES = {
  NAVBAR: "NAVBAR",
  SIDE_NAVBAR: "SIDE_NAVBAR",
};
