export const PRODUCT_ACTIONS = {
  PRODUCT_FETCH_STORE: {
    LOADING: "PRODUCT_FETCH_STORE_LOADING",
    SUCCESS: "PRODUCT_FETCH_STORE_SUCCESS",
    FAIL: "PRODUCT_FETCH_STORE_FAIL",
  },

  PRODUCT_FETCH_PRODUCTS: {
    LOADING: "PRODUCT_FETCH_PRODUCTS_LOADING",
    SUCCESS: "PRODUCT_FETCH_PRODUCTS_SUCCESS",
    FAIL: "PRODUCT_FETCH_PRODUCTS_FAIL",
  },
  PRODUCT_FETCH_SINGLE: {
    LOADING: "PRODUCT_FETCH_SINGLE_LOADING",
    SUCCESS: "PRODUCT_FETCH_SINGLE_SUCCESS",
    FAIL: "PRODUCT_FETCH_SINGLE_FAIL",
  },
};
