export const USER_ACTIONS = {
  SIGN_UP: {
    SUCCESS: "USER_SIGN_UP_SUCCESS",
    FALL: "USER_SIGN_UP_FALL",
    LOADING: "USER_SIGN_UP_LOADING",
  },
  LOGIN: {
    SUCCESS: "USER_LOGIN_SUCCESS",
    FALL: "USER_LOGIN_FALL",
    LOADING: "USER_LOGIN_LOADING",
  },
  UPDATE_INFO: {
    SUCCESS: "USER_UPDATE_INFO_SUCCESS",
    FALL: "USER_UPDATE_INFO_FALL",
    LOADING: "USER_UPDATE_INFO_LOADING",
  },
  GET_ME: {
    SUCCESS: "USER_GET_ME_SUCCESS",
    FAIL: "USER_GET_ME_FALL",
    LOADING: "USER_GET_ME_LOADING",
  },
  UPDATE_FIELD: "USER_UPDATE_FIELD",
  AUTO_LOGIN: "USER_AUTO_LOGIN",
  LOGOUT: "USER_LOGOUT",
  CREATE_USER_ERROR: "USER_CREATE_USER_ERROR",
  RESET_SUCCESS: "USER_RESET_SUCCESS",
};
