export const USER_ACTIONS = {
  SIGN_UP: {
    SUCCESS: "SIGN_UP_SUCCESS",
    FALL: "SIGN_UP_FALL",
    LOADING: "SIGN_UP_LOADING",
  },
  LOGIN: {
    SUCCESS: "LOGIN_SUCCESS",
    FALL: "LOGIN_FALL",
    LOADING: "LOGIN_LOADING",
  },
  UPDATE_FIELD: "UPDATE_FIELD",
  AUTO_LOGIN: "AUTO_LOGIN",
  LOGOUT: "LOGOUT",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",
};
