export const ICONS_ID = {
  IconInstaComments: "icon-insta-comments",
  IconSupportWhite: "icon-support-white",
  IconClose: "icon-close",
  IconYoutube: "icon-youtube",
  IconInstagram: "icon-instagram",
  IconPinterest: "icon-pinterest",
  IconFacebook: "icon-facebook",
  IconTwitter: "icon-twitter",
  IconAirplane: "icon-airplane",
  IconLogoBlue: "icon-logo-blue",
  IconDeal: "icon-deal",
  IconMnsRewards: "icon-mns-rewards",
  IconLike: "icon-like",
  IconCustomerSupport: "icon-customer-support",
  IconMnsRewardsWhite: "icon-mns-rewards-white",
  IconShare: "icon-share",
};
