export const topDealsProductsData = [
  {
    href: "/store/perfect-sports-apex-grass-fed-whey-protein.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/e7aba0/240/0/apex_whey_5lbs_chocolate_ice_cream.jpg",
    title: "PERFECT Sports APEX Grass-Fed, 5lbs",
    deal: "LIMITED TIME PRICE CUT",
    price: 49.99,
  },
  {
    href: "/store/nitro-tech-100-whey-gold.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/fac6e7/240/0/whey_gold_5lb_double_rich_chocolate.jpg",
    title: "MuscleTech Nitro-Tech 100% Whey Gold, 5lbs",
    deal: "EXTRA 30% OFF",
    price: 45.49,
  },
  {
    href: "/store/primeval-labs-eaa-max-energy.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/5a2836/240/0/island_punch_front_3_3.jpg",
    title: "Primeval Labs EAA MAX ENERGY, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/vitaform.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/6793a5/240/0/vitaform-60-tabs.jpg",
    title: "Allmax Vitaform, 60 Tablets",
    deal: "Buy 1 Get 1 FREE",
    price: 19.99,
  },
  {
    href: "/store/r1-creatine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/f6c717/240/0/rule1__creatine_30ser_new.jpg",
    title: "Rule 1 R1 Creatine, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/musclepharm-bcaa-powder.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/c05dd3/240/0/mpe_bcaa_30serv_watermelon_1_2.jpg",
    title: "MP Essentials BCAA, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 24.99,
  },
  {
    href: "/store/omega-3.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/b1dcf0/240/0/now_omega-3_1_2.jpg",
    title: "NOW Foods Omega-3, 200 Softgels",
    deal: "Buy 1 Get 1 FREE",
    price: 17.99,
  },
  {
    href: "/store/lipo-6-black-uc.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/98c306/240/0/lipo6blackucbox17_1_16.jpg",
    title: "Nutrex Lipo-6 Black UC, 60 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/c4-g4.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/f2247e/240/0/c4_original_30serv_cl_1.jpg",
    title: "Cellucor C4, 30 Servings",
    deal: "Buy 2 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/ripper.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/06bad4/240/0/the-ripper-blood-orange-30-serve.jpg",
    title: "JNX Sports The Ripper, 30 Servings",
    deal: "LIMITED TIME PRICE CUT",
    price: 17.99,
  },
  {
    href: "/store/force-factor-probioslim.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/57c857/240/0/probioslim30ct_bottlerender.jpg",
    title: "Force Factor ProbioSlim, 30 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 17.99,
  },
  {
    href: "/store/bpi-best-bcaa.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/c8573f/240/0/best_bcaa_30_servs_-arctic_ice-new_1_2.jpg",
    title: "BPI Best BCAA, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 27.99,
  },
];

export const topRatedProductsData = [
  {
    href: "/store/nitro-tech-performance.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/590990/240/0/nitro_tech_whey_protein_4lbs_vanilla.jpg",
    title: "MuscleTech Nitro-Tech Protein, 4lbs",
    deal: "EXTRA 30% OFF",
    price: 41.99,
  },
  {
    href: "/store/musclepharm-combat-100-whey-protein.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/0e6ad6/240/0/mp_100_combat_whey_small_1_1_1_3.jpg",
    title: "MP Combat 100% Whey, 5lbs",
    deal: "LIMITED TIME PRICE CUT",
    price: 49.99,
  },
  {
    href: "/store/scivation-xtend.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/0dc9a7/240/0/glacial_grape_-_xtend_30_9.jpg",
    title: "Scivation XTend, 30 Servings",
    deal: "30% DISCOUNT IN CART",
    price: 36.99,
  },
  {
    href: "/store/primeval-labs-apeshit-cutz.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/210f7a/240/0/apesh-t-cutz-smashberry.jpg",
    title: "Primeval Labs APESH*T Cutz, 50 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/test-x180.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/969da8/240/0/testx18060ct_bottlerender.jpg",
    title: "Force Factor Test X180, 60 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 34.99,
  },
  {
    href: "/store/r1-lbs.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/542817/240/0/R1_LBS_10_Choc_2.jpg",
    title: "Rule 1 R1 LBS, 6lbs",
    deal: "Buy 1 Get 1 FREE",
    price: 53.99,
  },
  {
    href: "/store/man-sports-scorch-powder.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/7b82b5/240/0/scorch-powder-75sv-peach-rings.jpg",
    title: "MAN Sports Scorch, 75 Serving",
    deal: "30% DISCOUNT IN CART",
    price: 29.99,
  },
  {
    href: "/store/isoflex.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/2811eb/240/0/isoflex_2lb-chocmint_20160209155609-sm_1_1.jpg",
    title: "AllMAX IsoFlex, 2lbs",
    deal: "Buy 2 for $69.99",
    price: 49.99,
  },
  {
    href: "/store/rcss-yeah-buddy.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/6ca250/240/0/YB_30srv_MP_1000_1.jpg",
    title: "RCSS Yeah Buddy, 30 Servings",
    deal: "PRICE CUT + FREE BETA-ALANINE 50ct",
    price: 24.99,
  },
  {
    href: "/store/bpi-sports-cla-plus-carnitine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/be10f2/240/0/cla_carnitine_-_50_servs_-_fruit_punch-new_1_10.jpg",
    title: "BPI CLA + Carnitine, 50 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 32.99,
  },
  {
    href: "/store/usn-bcaa-amino-plus-powder.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/1a8374/240/0/bcaa_amino_30_servings_greenapple.jpg",
    title: "USN BCAA Amino+, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 28.99,
  },
  {
    href: "/store/perfect-sports-diesel-whey-protein-isolate.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/c2d0d4/240/0/diesel_2lbs_milk_chocolate.jpg",
    title: "PERFECT Sports DIESEL, 2lbs",
    deal: "Buy 2 Get 1 FREE",
    price: 49.99,
  },
];

export const trendingProductsData = [
  {
    href: "/store/primeval-labs-apeshit.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/94e960/240/0/apesh-t-untamed-smashberry_1.jpg",
    title: "Primeval Labs APESH*T, 40 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/nutrex-lipo-6-defining-gel.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/5ed3e3/240/0/lipo6defgel.jpg",
    title: "Nutrex Lipo-6 Defining Gel, 4oz",
    deal: "Buy 1 Get 1 FREE",
    price: 34.97,
  },
  {
    href: "/store/acuts.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/b3c3c9/240/0/acuts_large_5.jpg",
    title: "AllMax AminoCuts, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 21.99,
  },
  {
    href: "/store/muscletech-cell-tech-hardcore.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/52c730/240/0/masstech_elite_7lbs_vanilla_cake.jpg",
    title: "MuscleTech Cell-Tech, 6lbs",
    deal: "EXTRA 30% OFF",
    price: 41.99,
  },
  {
    href: "/store/nutrex-isofit.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/625202/240/0/isofit-chocolate-shake-5lbs.jpg",
    title: "Nutrex ISOFIT, 5lbs",
    deal: "LIMITED TIME PRICE CUT",
    price: 59.99,
  },
  {
    href: "/store/iso-amino.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/7eebba/240/0/ISO-Amino-BB-0-STR_3.jpg",
    title: "MAN Sports ISO-Amino, 30 Servings",
    deal: "LIMITED TIME PRICE CUT",
    price: 14.99,
  },
  {
    href: "/store/r1-charged-creatine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/5ecb43/240/0/30_servings_blue_razz_lemonade_1.jpg",
    title: "Rule 1 Charged Creatine, 30 Servings",
    deal: "Buy 2 for $39.99",
    price: 33.99,
  },
  {
    href: "/store/now-nac-1000mg-tablets.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/9dc530/240/0/nac_1000mg_120_tablets.jpg",
    title: "NOW Foods NAC 1000mg, 120 Tabs",
    deal: "LIMITED TIME PRICE CUT",
    price: 15.99,
  },
  {
    href: "/store/cobra-labs-curse.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/3bfc25/240/0/the-curse-lemon-rush-50-serve.jpg",
    title: "JNX Sports The Curse, 50 Servings",
    deal: "LIMITED TIME PRICE CUT",
    price: 19.99,
  },
  {
    href: "/store/usn-phedracut-water-x-diuretic.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/39e504/240/0/phedracut_waterx_new_look_1.jpg",
    title: "USN PhedraCut Water X, 90 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 14.99,
  },
  {
    href: "/store/rcss-l-carnitine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/1960d2/240/0/l-carnitine-xs-3000-blue-razz.jpg",
    title: "RCSS L-Carnitine 3000, 31 Servings",
    deal: "BOGO + FREE Fizzique RTD",
    price: 34.99,
  },
  {
    href: "/store/perfect-sports-iprep.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/d005b3/240/0/iprep-orange-gummy-bear--us.jpg",
    title: "PERFECT Sports iPrep, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 24.99,
  },
];

export const proteinCategories = {
  bannerData: {
    href: "/store/brands/allmax",
    isSale: false,
    srcset:
      "https://cdn.muscleandstrength.com/store/media/merchandising/2_21_Allmax_BP_Mobile_1.jpg",
    media: "(max-width: 839px)",
    src: "https://cdn.muscleandstrength.com/store/media/merchandising/2_21_Allmax_BP_Desktop_1.jpg",
    alt: "Demand More, Get Allmax - The trusted brand of athletes and fitness enthusiasts on sale now",
  },
  title: "protein",
  subCategories: [
    {
      title: "Whey Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein.html",
      products: [
        "/store/bpi-whey-hd.html",
        "/store/six-star-100-whey-protein-plus.html",
        "/store/nitro-tech-100-whey-gold.html",
        "/store/nitro-tech-performance.html",
        "/store/musclepharm-combat-100-whey-protein.html",
        "/store/bpi-best-protein.html",
        "/store/nitro-tech-performance.html",
        "/store/dymatize-iso-100.html",
        "/store/nitro-tech-ripped.html",
        "/store/isoflex.html",
        "/store/nitro-tech-performance.html",
        "/store/bpisports-isohd-whey-protein.html",
        "/store/allmax-allwhey-gold.html",
        "/store/100-whey-gold-standard.html",
        "/store/perfect-sports-apex-grass-fed-whey-protein.html",
        "/store/100-whey-gold-standard.html",
        "/store/nitro-tech-100-whey-gold.html",
        "/store/dymatize-iso-100.html",
        "/store/allmax-allwhey-classic.html",
        "/store/isoflex.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/r1-lbs.html",
        "/store/r1-whey-blend.html",
        "/store/nitro-tech-ripped.html",
        "/store/impact-whey.html",
        "/store/allmax-allwhey-gold.html",
        "/store/muscletech-grass-fed-whey.html",
        "/store/rcss-king-whey.html",
        "/store/nitro-tech-performance.html",
        "/store/isonatural.html",
        "/store/muscle-gauge-whey-protein-isolate.html",
        "/store/impact-whey-isolate.html",
        "/store/syntha-6.html",
        "/store/impact-whey.html",
        "/store/elite-whey-protein.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/r1-whey-blend.html",
        "/store/premier-protein-100percent-whey.html",
        "/store/cor-performance-whey.html",
        "/store/platinum-hydrowhey.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/r1-whey-blend.html",
        "/store/impact-whey-isolate.html",
        "/store/isopure.html",
        "/store/allmax-allwhey-classic.html",
        "/store/rivalus-rival-whey.html",
        "/store/isonatural.html",
        "/store/syntha-6.html",
        "/store/rivalus-promasil.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/six-star-whey-isolate.html",
        "/store/isoflex.html",
      ],
    },
    {
      title: "Vegan Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/vegan-protein-supplements.html",
      products: [
        "/store/barebells-plant-based-protein-bar.html",
        "/store/orgain-organic-protein.html",
        "/store/orgain-organic-meal.html",
        "/store/orgain-organic-protein.html",
        "/store/bpi-sports-veggie-protein.html",
        "/store/orgain-organic-protein-superfoods.html",
        "/store/vegan-organic-nutrition-shake.html",
        "/store/nutrex-plant-protein.html",
        "/store/orgain-organic-protein-superfoods.html",
        "/store/raw-fusion.html",
        "/store/purely-inspired-organic-protein.html",
        "/store/vegan-joy.html",
        "/store/orgain-organic-protein.html",
        "/store/keto-plant-protein.html",
        "/store/complete-plant-protein.html",
        "/store/orgain-sport-protein.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/perfect-sports-diesel-vegan.html",
        "/store/mhp-fit-lean-plant-protein.html",
        "/store/now-plant-protein-complex.html",
        "/store/powerful-plant-based-protein-shake.html",
        "/store/now-soy-protein-isolate.html",
        "/store/orgain-sport-protein.html",
        "/store/raw-fusion.html",
        "/store/gaspari-proven-vegan-protein.html",
        "/store/sinfit-plant-based-crunch-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/r1-plant-protein.html",
        "/store/swolverine-plant-protein.html",
        "/store/simple-protein.html",
        "/store/fnx-reform.html",
        "/store/raw-fusion.html",
        "/store/complete-cookie.html",
        "/store/vegan-protein.html",
        "/store/powerful-plant-based-protein-shake.html",
        "/store/orgain-organic-protein-greens.html",
        "/store/100-plant-protein.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/v-pro.html",
        "/store/prosupps-plant-perform.html",
        "/store/finaflex-opp-vegan-drink-mix.html",
        "/store/complete-cookie.html",
        "/store/myprotein-vegan-protein-bar.html",
        "/store/r1-plant-protein-energy.html",
        "/store/v-pro.html",
        "/store/now-organic-pumpkin-seed-protein.html",
        "/store/perfect-sports-diesel-vegan.html",
        "/store/orgain-organic-protein.html",
        "/store/vegan-protein.html",
      ],
    },
    {
      title: "Protein Bars",
      href: "https://www.muscleandstrength.com/store/category/protein/bars.html",
      products: [
        "/store/r1-bar1.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/allmax-protein-snackbar.html",
        "/store/barebells-protein-bar.html",
        "/store/r1-bar1-smooth.html",
        "/store/barebells-protein-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/primebites-protein-brownies.html",
        "/store/authentic-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/authentic-bar.html",
        "/store/allmax-protein-snackbar.html",
        "/store/on-protein-wafers.html",
        "/store/primebites-protein-brownies.html",
        "/store/quest-bar.html",
        "/store/authentic-bar.html",
        "/store/gaspari-ageless-collagen-protein-bars.html",
        "/store/on-protein-wafers.html",
        "/store/sinfit-crunch-bar.html",
        "/store/sinfit-plant-based-crunch-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/mp-combat-crunch-bars.html",
        "/store/r1-bar1-smooth.html",
        "/store/bsn-syntha-6-protein-crisp-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/mp-combat-crunch-bars.html",
        "/store/bsn-syntha-6-protein-crisp-bar.html",
        "/store/grenade-carb-killa-bars.html",
        "/store/layered-bar.html",
        "/store/rcss-king-cake.html",
        "/store/myprotein-triple-stack-bars.html",
        "/store/quest-bar.html",
        "/store/obvi-bar.html",
        "/store/r1-bar1.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/quest-hero-bar.html",
        "/store/obvi-bar.html",
        "/store/myprotein-vegan-protein-bar.html",
        "/store/quest-snack-bar.html",
        "/store/grenade-carb-killa-bars.html",
        "/store/animal-pro-bar.html",
        "/store/myprotein-triple-stack-bars.html",
        "/store/layered-bar.html",
        "/store/sinfit-crunch-bar.html",
      ],
    },
    {
      title: "Whey Protein Isolate",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein-isolate.html",
      products: [
        "/store/dymatize-iso-100.html",
        "/store/isoflex.html",
        "/store/perfect-sports-diesel-whey-protein-isolate.html",
        "/store/bpisports-isohd-whey-protein.html",
        "/store/man-sports-isolate-protein-powder.html",
        "/store/dymatize-iso-100.html",
        "/store/isoflex.html",
        "/store/fizzique-sparkling-protein-water.html",
        "/store/nutrex-isofit.html",
        "/store/impact-clear-whey-isolate.html",
        "/store/muscletech-iso-whey-clear-protein.html",
        "/store/usn-zero-carb-isopro-whey-protein-isolate.html",
        "/store/isonatural.html",
        "/store/muscle-gauge-whey-protein-isolate.html",
        "/store/impact-whey-isolate.html",
        "/store/fizzique-sparkling-protein-water.html",
        "/store/r1-protein.html",
        "/store/now-whey-protein-isolate.html",
        "/store/swolverine-whey-protein-isolate.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/nutrex-isofit.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/platinum-hydrowhey.html",
        "/store/impact-whey-isolate.html",
        "/store/isopure.html",
        "/store/magnum-quattro.html",
        "/store/r1-protein.html",
        "/store/magnum-quattro.html",
        "/store/now-whey-protein-isolate.html",
        "/store/xtend-pro.html",
        "/store/xtend-pro.html",
        "/store/isonatural.html",
        "/store/usn-zero-carb-isopro-whey-protein-isolate.html",
        "/store/perfect-sports-diesel-whey-protein-isolate.html",
        "/store/now-whey-protein-isolate.html",
        "/store/r1-protein.html",
        "/store/six-star-whey-isolate.html",
        "/store/isoflex.html",
        "/store/isopure.html",
        "/store/iso-tropic-max.html",
        "/store/primeval-labs-isolit.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/magnum-quattro.html",
        "/store/muscle-gauge-whey-protein-isolate.html",
        "/store/magnum-quattro.html",
        "/store/perfect-sports-perfect-whey-concentrate.html",
        "/store/isopure.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
      ],
    },
    {
      title: "Whey Protein Blends",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein-blends.html",
      products: [
        "/store/nitro-tech-100-whey-gold.html",
        "/store/nitro-tech-performance.html",
        "/store/nitro-tech-performance.html",
        "/store/nitro-tech-ripped.html",
        "/store/nitro-tech-performance.html",
        "/store/allmax-allwhey-gold.html",
        "/store/100-whey-gold-standard.html",
        "/store/bpi-whey-hd.html",
        "/store/100-whey-gold-standard.html",
        "/store/nitro-tech-100-whey-gold.html",
        "/store/allmax-allwhey-classic.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/r1-lbs.html",
        "/store/r1-whey-blend.html",
        "/store/nitro-tech-ripped.html",
        "/store/allmax-allwhey-gold.html",
        "/store/nitro-tech-performance.html",
        "/store/syntha-6.html",
        "/store/elite-whey-protein.html",
        "/store/r1-whey-blend.html",
        "/store/cor-performance-whey.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/r1-whey-blend.html",
        "/store/usn-premium-100-whey-protein-plus.html",
        "/store/magnum-quattro.html",
        "/store/allmax-allwhey-classic.html",
        "/store/magnum-quattro.html",
        "/store/rivalus-promasil.html",
        "/store/rivalus-rival-whey.html",
        "/store/syntha-6.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/magnum-quattro.html",
        "/store/magnum-quattro.html",
        "/store/syntha-6.html",
        "/store/fnx-restart.html",
        "/store/core-nutritionals-mrp.html",
        "/store/rivalus-rival-whey.html",
        "/store/rivalus-rival-whey.html",
        "/store/elite-whey-protein.html",
        "/store/fnx-refuel.html",
        "/store/gaspari-myofusion-advanced.html",
        "/store/r1-lbs.html",
        "/store/ovbi-kids-complete-protein.html",
        "/store/natural-whey.html",
        "/store/promore.html",
        "/store/gaspari-myofusion-advanced.html",
      ],
    },
    {
      title: "Multi-Protein Blends",
      href: "https://www.muscleandstrength.com/store/category/protein/protein-blends.html",
      products: [
        "/store/combat-powder.html",
        "/store/combat-powder.html",
        "/store/phase8.html",
        "/store/hexapro.html",
        "/store/hexapro.html",
        "/store/raw-fusion.html",
        "/store/primebites-protein-brownies.html",
        "/store/organic-nutrition-shake.html",
        "/store/pro-antium.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/powerful-protein-shake.html",
        "/store/usn-premium-100-whey-protein-plus.html",
        "/store/kids-protein-shake.html",
        "/store/mhp-probolic-sr.html",
        "/store/rivalus-promasil.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/mhp-probolic-sr.html",
        "/store/raw-fusion.html",
        "/store/rivalus-promasil.html",
        "/store/primebites-protein-brownies.html",
        "/store/syntha-6-isolate.html",
        "/store/core-nutritionals-mrp.html",
        "/store/syntha-6-isolate.html",
        "/store/powerful-protein-shake.html",
        "/store/beast-protein.html",
        "/store/raw-fusion.html",
        "/store/real-carbs-plus-protein.html",
        "/store/powerful-protein-shake.html",
        "/store/combat-powder.html",
        "/store/delight.html",
        "/store/sinfit-peanut-powder.html",
        "/store/clean-protein-shake.html",
        "/store/combat-powder.html",
      ],
    },
    {
      title: "Casein Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/casein-protein.html",
      products: [
        "/store/elite-series-casein-protein.html",
        "/store/r1-casein.html",
        "/store/100-casein-protein.html",
        "/store/r1-casein.html",
        "/store/elite-casein.html",
        "/store/casein-fx.html",
        "/store/elite-casein.html",
        "/store/100-casein-protein.html",
        "/store/core-nutritionals-mrp.html",
        "/store/natural-100-casein-gold-standard.html",
        "/store/fnx-retire.html",
        "/store/musclepharm-combat-casein.html",
        "/store/natural-100-casein-gold-standard.html",
      ],
    },
    {
      title: "Extended Release Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/extended-release-protein.html",
      products: [
        "/store/combat-powder.html",
        "/store/combat-powder.html",
        "/store/phase8.html",
        "/store/syntha-6.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/usn-premium-100-whey-protein-plus.html",
        "/store/mhp-probolic-sr.html",
        "/store/syntha-6.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/mhp-probolic-sr.html",
        "/store/syntha-6.html",
        "/store/syntha-6-isolate.html",
        "/store/syntha-6-isolate.html",
        "/store/beast-protein.html",
        "/store/combat-powder.html",
        "/store/combat-powder.html",
      ],
    },
    {
      title: "Naturally Flavored Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/naturally-flavored-protein.html",
      products: [
        "/store/keto-plant-protein.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/now-soy-protein-isolate.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/natural-whey.html",
        "/store/vegan-protein.html",
        "/store/100-plant-protein.html",
        "/store/natural-100-casein-gold-standard.html",
        "/store/natural-isolate.html",
        "/store/orgain-grass-fed-whey.html",
        "/store/natural-whey.html",
        "/store/natural-100-casein-gold-standard.html",
        "/store/natural-isopure.html",
        "/store/natural-isolate.html",
        "/store/vegan-protein.html",
        "/store/simple-protein.html",
        "/store/isopure.html",
        "/store/clean-protein-shake.html",
      ],
    },
    {
      title: "Whey Protein Hydrolysate",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein-hydrolysate.html",
      products: [
        "/store/bpisports-isohd-whey-protein.html",
        "/store/r1-protein.html",
        "/store/platinum-hydrowhey.html",
        "/store/r1-protein.html",
        "/store/r1-protein.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/platinum-hydrowhey.html",
        "/store/gaspari-nutrition-proven-whey.html",
        "/store/gaspari-nutrition-proven-whey.html",
      ],
    },
    {
      title: "Beef Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/beef-protein.html",
      products: [
        "/store/stryve-biltong-stick.html",
        "/store/carnivor-mass.html",
        "/store/carnivor.html",
        "/store/carnivor.html",
        "/store/big-steer-1250.html",
        "/store/carnivor.html",
        "/store/stryve-biltong.html",
        "/store/carnivor.html",
        "/store/carnivor-mass.html",
        "/store/vacadillos-carne-seca.html",
        "/store/carnivor.html",
        "/store/carnivor-lean-meal.html",
        "/store/carnivor-coffee.html",
        "/store/stryve-biltong-stick.html",
        "/store/carnivor-coffee.html",
        "/store/beef-biltong.html",
        "/store/beef-biltong.html",
      ],
    },
  ],
};

export const preWorkoutCategories = {
  bannerData: {
    href: "/store/brands/ronnie-coleman-signature-series",
    isSale: false,
    srcset:
      "https://cdn.muscleandstrength.com/store/media/merchandising/7_18_RCSS_BP_Mobile_1_1.jpg",
    media: "(max-width: 839px)",
    src: "https://cdn.muscleandstrength.com/store/media/merchandising/7_18_RCSS_BP_Desktop_1_1.jpg",
    alt: "Save Big on Ronnie Coleman! Buy 1 get 1 free deals, price cuts, and more!",
  },
  title: "pre-workout",
  subCategories: [
    {
      title: "Stimulant Free",
      href: "https://www.muscleandstrength.com/store/category/pre-workout/stimulant-free.html",
      products: [
        "/store/impact-pump.html",
        "/store/apeshit-pumps.html",
        "/store/no3-chrome-g4.html",
        "/store/glycergrow.html",
        "/store/swolverine-pre.html",
        "/store/pumpsurge.html",
        "/store/glaxon-plasm-surge.html",
        "/store/fnx-reinforce.html",
        "/store/legacy-series-pump.html",
        "/store/dr-jekyll-stim-free.html",
        "/store/dr-jekyll-signature-series.html",
        "/store/eflow-enflate.html",
        "/store/prosupps-no3-drive.html",
      ],
    },
    {
      title: "High Stimulant",
      href: "https://www.muscleandstrength.com/store/category/pre-workout/high-stimulant.html",
      products: [
        "/store/usn-3xt-max-energy.html",
        "/store/impact-igniter.html",
        "/store/rcss-yeah-buddy.html",
        "/store/perfect-sports-iprep.html",
        "/store/primeval-labs-apeshit-rtd.html",
        "/store/hemo-rage-unleashed.html",
        "/store/stimul8-hardcore.html",
        "/store/allmax-igniter-sport.html",
        "/store/rcss-yeah-buddy.html",
        "/store/nitraflex.html",
        "/store/rcss-yeah-buddy.html",
        "/store/c4-ultimate.html",
        "/store/superpump-aggression.html",
        "/store/nutrex-outlift.html",
        "/store/usn-3xt-max-energy.html",
        "/store/muscletech-shatter-elite.html",
        "/store/bucked-up-woke-af-pre-workout.html",
        "/store/man-sports-game-day-v2.html",
        "/store/musclemeds-nitrotest.html",
        "/store/game-day-nootropic.html",
        "/store/nutrex-outlift.html",
        "/store/mr-hyde-nitro-x-pre-workout.html",
        "/store/5-percent-5150.html",
        "/store/prosupps-hyde-energy.html",
        "/store/glaxon-specimen-gfy.html",
        "/store/primeval-labs-apeshit-rtd.html",
        "/store/shatter.html",
        "/store/mr-hyde-test-surge.html",
        "/store/magnum-limitless.html",
        "/store/prosupps-hyde-pre-workout.html",
        "/store/beast-mode-black.html",
        "/store/universal-animal-fury.html",
        "/store/prosupps-hyde-energy.html",
        "/store/glaxon-specimen-worldwide.html",
        "/store/nutrex-outlift.html",
        "/store/fnx-recharge-plus.html",
        "/store/broken-arrow.html",
        "/store/gat-pmp.html",
        "/store/gat-pmp.html",
        "/store/hyper-crush.html",
        "/store/bsn-endorush-powder.html",
        "/store/universal-animal-fury.html",
        "/store/prosupps-hyde-xtreme-rtd.html",
        "/store/eflow-enrage.html",
        "/store/eflow-nutrition-enrage-black.html",
        "/store/nutrex-warrior-preworkout.html",
        "/store/glaxon-specimen-yo-yo.html",
        "/store/core-nutritionals-fury.html",
        "/store/ap-regimen-pre-workout-rtd.html",
        "/store/ap-regimen-pre-workout-rtd.html",
      ],
    },
    {
      title: "Creatine Free",
      href: "https://www.muscleandstrength.com/store/category/pre-workout/creatine-free.html",
      products: [
        "/store/usn-3xt-max-energy.html",
        "/store/primeval-labs-eaa-max-energy.html",
        "/store/stimul8-hardcore.html",
        "/store/nitraflex.html",
        "/store/usn-3xt-power.html",
        "/store/c4-ripped.html",
        "/store/bucked-up-pre-workout.html",
        "/store/usn-3xt-max-energy.html",
        "/store/muscletech-shatter-elite.html",
        "/store/explosion-pre-workout.html",
        "/store/b4.html",
        "/store/glycergrow.html",
        "/store/musclemeds-nitrotest.html",
        "/store/swolverine-pre.html",
        "/store/redefine-nutrition-stimul8.html",
        "/store/stryve-pre-workout.html",
        "/store/nitrosurge.html",
        "/store/ronnie-coleman-pre-xs-powder.html",
        "/store/storm-pre-workout.html",
        "/store/incinr8-hardcore.html",
        "/store/havok-v2.html",
        "/store/ap-regimen-pre-workout.html",
        "/store/broken-arrow.html",
        "/store/eflow-nutrition-enrage-black.html",
        "/store/ap-regimen-pre-workout-rtd.html",
        "/store/ronnie-coleman-pre-xs-powder.html",
        "/store/beast-mode-x.html",
        "/store/ap-regimen-pre-workout-rtd.html",
      ],
    },
    {
      title: "Fat Loss Pre-Workouts",
      href: "https://www.muscleandstrength.com/store/category/pre-workout/fat-loss-pre-workout.html",
      products: [
        "/store/primeval-labs-apeshit-cutz.html",
        "/store/acuts.html",
        "/store/muscletech-vapor-x5-ripped.html",
        "/store/perfect-sports-ilean.html",
        "/store/man-sports-scorch-powder.html",
        "/store/c4-ripped.html",
        "/store/shatter-ripped.html",
        "/store/c4-ultimate-shred.html",
        "/store/c4-ripped-sport.html",
        "/store/primeval-labs-apeshit-cutz.html",
        "/store/redefine-nutrition-stimul8.html",
        "/store/magnum-fasted-cardio.html",
        "/store/lfg-burn-pre-workout.html",
        "/store/nitrosurge-shred.html",
        "/store/incinr8-hardcore.html",
        "/store/beast-mode-burn.html",
        "/store/prosupps-hyde-thermo.html",
        "/store/perfect-sports-burn-cycle.html",
        "/store/storm-burn.html",
      ],
    },
    {
      title: "Pre-Workout Pump",
      href: "https://www.muscleandstrength.com/store/category/pre-workout/pre-workout-pump.html",
      products: [
        "/store/usn-3xt-max-energy.html",
        "/store/impact-pump.html",
        "/store/apeshit-pumps.html",
        "/store/no3-chrome-g4.html",
        "/store/usn-3xt-max-energy.html",
        "/store/no-xplode-vaso.html",
        "/store/pumpsurge.html",
        "/store/pump-pro.html",
        "/store/animal-pump.html",
        "/store/prosupps-hyde-pre-workout.html",
        "/store/vasogorge.html",
        "/store/glaxon-plasm-surge.html",
        "/store/legacy-series-pump.html",
        "/store/gat-pmp.html",
        "/store/gat-pmp.html",
        "/store/eflow-enflate.html",
        "/store/no-xplode-vaso.html",
      ],
    },
  ],
};

export const generalHealthCategories = {
  title: "general-health",
  subCategories: [
    {
      title: "Immune Support",
      href: "https://www.muscleandstrength.com/store/category/general-health/immune-system.html",
      products: [
        "/store/core-fish-oil.html",
        "/store/now-nac-1000mg-tablets.html",
        "/store/now-ashwagandha.html",
        "/store/now-zinc-50mg-tablets.html",
        "/store/now-nac-600mg-capsules.html",
        "/store/organic-superfoods-immunity-up.html",
        "/store/now-nac-600mg-capsules.html",
        "/store/now-zinc-50mg-tablets.html",
        "/store/now-quercetin-with-bromelain-vcaps.html",
        "/store/now-zinc-picolinate-50mg.html",
        "/store/now-c-1000-sustained-release.html",
        "/store/now-mega-d-3-and-mk-7.html",
        "/store/now-zinc-picolinate-50mg.html",
        "/store/now-epicor-plus-immunity.html",
        "/store/c-500-with-rose-hips.html",
        "/store/now-whole-psyllium-husks.html",
        "/store/orange-triad.html",
        "/store/now-glutathione.html",
        "/store/orange-triad.html",
        "/store/now-l-lysine-1000mg-tablets.html",
        "/store/orange-triad-plus-greens.html",
        "/store/now-vitamin-c-1000-tablets-rh-bioflavonoids.html",
        "/store/goli-acv-gummies.html",
        "/store/now-astragalus-500mg-vcaps.html",
        "/store/american-metabolix-turmeric-gummies.html",
        "/store/now-vitamin-c-1000-vcaps-w-100mg-bioflavonoids.html",
        "/store/usn-vibrance-immune-health.html",
        "/store/mhp-fit-lean-immune-greens.html",
        "/store/biotin.html",
        "/store/swolverine-krill-oil.html",
        "/store/better-turmeric-soft-chews.html",
        "/store/swolverine-ashwagandha-gummies.html",
        "/store/now-allibiotic-cf.html",
        "/store/better-turmeric-tablets.html",
        "/store/now-elderberry-500mg.html",
        "/store/now-vitamin-c-1000-tablets-rh-bioflavonoids.html",
        "/store/now-vitamin-a.html",
        "/store/force-factor-nac.html",
        "/store/perfect-sports-shield-plus-vitamin-c.html",
        "/store/now-ashwagandha-liquid.html",
        "/store/force-factor-immunity.html",
        "/store/green-supreme-fusion.html",
        "/store/now-probiotic-10-25-billion.html",
        "/store/now-chewable-c-500.html",
        "/store/now-l-optizinc-30mg-veg-caps.html",
        "/store/mhp-fit-lean-immune-reds.html",
        "/store/now-vitamin-c-1000-vcaps-w-100mg-bioflavonoids.html",
        "/store/now-colostrum-500mg-vcaps.html",
        "/store/force-factor-leanfire-acv-gummies.html",
        "/store/nutritox-vibrance.html",
        "/store/now-respir-all-tablets.html",
        "/store/now-elderberry-and-zinc-lozenges.html",
        "/store/ovbi-pinks-superfood-and-immunity-blend.html",
        "/store/san-calcium-magnesium-zinc-d3.html",
        "/store/biotin.html",
        "/store/now-vitamin-c-complex-buffered-tablets.html",
        "/store/now-vitamin-c-1000-vcaps-w-100mg-bioflavonoids.html",
        "/store/glaxon-supershrooms.html",
      ],
    },
    {
      title: "Fiber",
      href: "https://www.muscleandstrength.com/store/category/general-health/fiber.html",
      products: [
        "/store/force-factor-probioslim-prebiotic-fiber.html",
        "/store/now-whole-psyllium-husks.html",
        "/store/smarter-greens-digestion-powder.html",
        "/store/proven-fiber.html",
        "/store/now-psyllium-husk-powder.html",
        "/store/now-apple-pectin.html",
        "/store/fiber-3.html",
        "/store/now-whole-psyllium-husks.html",
        "/store/now-psyllium-husk-capsules.html",
        "/store/now-psyllium-husk-powder.html",
      ],
    },
    {
      title: "Collagen",
      href: "https://www.muscleandstrength.com/store/category/general-health/collagen.html",
      products: [
        "/store/allmax-collagen-biotin-vitamin-c.html",
        "/store/orgain-collagen-peptides.html",
        "/store/321glo-collagen-cookie.html",
        "/store/nutrex-collagen.html",
        "/store/usn-vibrance-weight-loss-collagen.html",
        "/store/collagen-peptides-superfoods.html",
        "/store/321glo-collagen-brownie.html",
        "/store/ovbi-super-collagen-protein.html",
        "/store/usn-vibrance-weight-loss-collagen.html",
        "/store/321glo-collagen-brownie.html",
        "/store/collagen-types-1-and-3.html",
        "/store/321glo-collagen-cookie.html",
        "/store/bone-broth-athletic-collagen.html",
        "/store/collagen-types-1-and-3.html",
        "/store/obvi-collagenic-burn.html",
        "/store/yourganics-collagen.html",
        "/store/usn-vibrance-collagen.html",
        "/store/r1-collagen-peptides.html",
        "/store/ap-regimen-c3.html",
        "/store/alpha-f.html",
        "/store/glaxon-wonder-collagen.html",
        "/store/now-uc-ii.html",
        "/store/stryve-collagen.html",
        "/store/swolverine-collagen.html",
        "/store/gaspari-ageless-collagen-protein-bars.html",
        "/store/nutritox-collagen-peptides.html",
        "/store/r1-collagen-peptides.html",
        "/store/amino-energy-plus-collagen.html",
        "/store/mhp-fit-lean-collagen-probiotics.html",
        "/store/collagen-types-1-and-3.html",
        "/store/isopure-collagen.html",
        "/store/fnx-resilience-collagen-protein.html",
        "/store/fnx-resilience-collagen-gummies.html",
        "/store/ap-regimen-pure-collagen.html",
        "/store/h2obvi.html",
        "/store/obvi-collagen-whey-protein.html",
        "/store/now-aquatic-beauty.html",
        "/store/universal-nutrition-collagen.html",
      ],
    },
    {
      title: "Greens Food",
      href: "https://www.muscleandstrength.com/store/category/general-health/greens.html",
      products: [
        "/store/organic-superfoods.html",
        "/store/organic-superfoods-immunity-up.html",
        "/store/allmax-cytogreens.html",
        "/store/allmax-cytogreens.html",
        "/store/allmax-cytogreens.html",
        "/store/smarter-greens-daily-wellness-powder.html",
        "/store/orgain-organic-protein-superfoods.html",
        "/store/collagen-peptides-superfoods.html",
        "/store/orgain-organic-protein-superfoods.html",
        "/store/primeval-day2day-fruits-and-greens.html",
        "/store/orange-triad-plus-greens.html",
        "/store/smarter-greens-soft-chews.html",
        "/store/mhp-fit-lean-immune-greens.html",
        "/store/now-chlorella-1000mg.html",
        "/store/smarter-greens-gummies.html",
        "/store/glaxon-super-greens.html",
        "/store/smarter-greens-superfoods-powder.html",
        "/store/smarter-greens-digestion-powder.html",
        "/store/r1-energized-fruits-and-greens.html",
        "/store/now-certified-organic-spirulina.html",
        "/store/green-supreme-fusion.html",
        "/store/mhp-fit-lean-immune-reds.html",
        "/store/green-surge.html",
        "/store/greens-pak.html",
        "/store/orange-oximega-greens.html",
        "/store/goli-supergreens-gummies.html",
        "/store/ecogreen-multi.html",
        "/store/smarter-greens-energy-powder.html",
        "/store/fnx-rebalance.html",
        "/store/goli-superfruits-gummies.html",
        "/store/swolverine-greens-plus-reds.html",
        "/store/max-effort-greens.html",
        "/store/orgain-organic-protein-greens.html",
        "/store/universal-greens-powder.html",
        "/store/ap-regimen-greens.html",
        "/store/fnx-redemption.html",
        "/store/motiv8-greens.html",
        "/store/glaxon-super-greens.html",
        "/store/smarter-greens-tablets.html",
      ],
    },
    {
      title: "Prostate Support",
      href: "https://www.muscleandstrength.com/store/category/general-health/prostate-support.html",
      products: [
        "/store/now-prostate-support.html",
        "/store/force-factor-prostate-advanced.html",
        "/store/force-factor-prostate.html",
        "/store/saw-palmetto-extract.html",
        "/store/orange-healthiq.html",
        "/store/now-prostate-health.html",
        "/store/prostate-gummies.html",
        "/store/ff-saw-palmetto.html",
        "/store/now-pygeum-and-saw-palmetto.html",
        "/store/gaspari-ageless-prostate-health.html",
      ],
    },
    {
      title: "Cleansing/Detox",
      href: "https://www.muscleandstrength.com/store/category/general-health/cleansing.html",
      products: [
        "/store/goli-acv-gummies.html",
        "/store/gaspari-proven-liver-dtox.html",
        "/store/gat-sport-liver-cleanse.html",
        "/store/orange-healthiq.html",
        "/store/green-supreme-fusion.html",
        "/store/now-liver-detoxifier-and-regenerator.html",
        "/store/now-liver-detoxifier-and-regenerator.html",
        "/store/now-organic-dandelion-tea.html",
        "/store/obvi-detox.html",
        "/store/now-activated-charcoal.html",
        "/store/glaxon-c-tox.html",
        "/store/now-dim-200.html",
        "/store/now-liquid-chlorophyll.html",
        "/store/max-effort-greens.html",
        "/store/now-silymarin-milk-thistle-450mg.html",
        "/store/motiv8-detox.html",
        "/store/motiv8-acv-gummies.html",
        "/store/now-graviola-500mg.html",
        "/store/obvi-acv-gummies.html",
        "/store/now-glutathione.html",
      ],
    },
    {
      title: "Bone Health",
      href: "https://www.muscleandstrength.com/store/category/general-health/bone-health.html",
      products: [
        "/store/allmax-collagen-biotin-vitamin-c.html",
        "/store/now-d-3-and-k-2.html",
        "/store/now-mega-d-3-and-mk-7.html",
        "/store/now-mk-7-vitamin-k-2-100mcg.html",
        "/store/usn-vibrance-weight-loss-collagen.html",
        "/store/ovbi-super-collagen-protein.html",
        "/store/now-calcium-magnesium.html",
        "/store/now-magnesium-citrate.html",
        "/store/usn-vibrance-weight-loss-collagen.html",
        "/store/collagen-types-1-and-3.html",
        "/store/now-calcium-magnesium-tablets.html",
        "/store/bone-broth-athletic-collagen.html",
        "/store/collagen-types-1-and-3.html",
        "/store/obvi-collagenic-burn.html",
        "/store/usn-vibrance-collagen.html",
        "/store/yourganics-collagen.html",
        "/store/r1-collagen-peptides.html",
        "/store/now-vitamin-k-2.html",
        "/store/now-coral-calcium-1000mg.html",
        "/store/swolverine-collagen.html",
        "/store/glaxon-wonder-collagen.html",
        "/store/now-uc-ii.html",
        "/store/san-calcium-magnesium-zinc-d3.html",
        "/store/stryve-collagen.html",
        "/store/nutritox-collagen-peptides.html",
        "/store/now-calcium-citrate-powder.html",
        "/store/now-calcium-magnesium-tablets.html",
        "/store/mhp-fit-lean-collagen-probiotics.html",
        "/store/r1-collagen-peptides.html",
        "/store/now-calcium-magnesium.html",
        "/store/now-cal-mag-caps.html",
        "/store/collagen-types-1-and-3.html",
        "/store/fnx-resilience-collagen-protein.html",
        "/store/isopure-collagen.html",
        "/store/obvi-collagen-whey-protein.html",
        "/store/fnx-resilience-collagen-gummies.html",
        "/store/h2obvi.html",
        "/store/now-cal-mag-caps.html",
        "/store/universal-nutrition-collagen.html",
        "/store/now-coral-calcium-plus.html",
        "/store/now-calcium-citrate-caps.html",
        "/store/red-mineral-algae.html",
      ],
    },
    {
      title: "Digestive Health/Probiotics",
      href: "https://www.muscleandstrength.com/store/category/general-health/digestive-health.html",
      products: [
        "/store/force-factor-probioslim.html",
        "/store/organic-superfoods.html",
        "/store/organic-superfoods-immunity-up.html",
        "/store/now-super-enzymes.html",
        "/store/musclemeds-feast-mode.html",
        "/store/force-factor-probioslim-weight-loss-essentials.html",
        "/store/now-super-enzymes.html",
        "/store/purely-inspired-probiotics-plus-weight-loss.html",
        "/store/allmax-nutrition.html",
        "/store/force-factor-probioslim-prebiotic-fiber.html",
        "/store/force-factor-probioslim.html",
        "/store/orange-triad.html",
        "/store/now-whole-psyllium-husks.html",
        "/store/primeval-day2day-fruits-and-greens.html",
        "/store/force-factor-probioslim-extra-strength.html",
        "/store/usn-apple-cider-vinegar.html",
        "/store/orange-triad.html",
        "/store/goli-acv-gummies.html",
        "/store/now-candida-support.html",
        "/store/bone-broth-athletic-collagen.html",
        "/store/force-factor-probioslim-acv-gummies.html",
        "/store/obvi-collagenic-burn.html",
        "/store/man-propf3.html",
        "/store/better-turmeric-tablets.html",
        "/store/orange-healthiq.html",
        "/store/green-supreme-fusion.html",
        "/store/now-probiotic-10-25-billion.html",
        "/store/anavite-multi-pack.html",
        "/store/now-psyllium-husk-powder.html",
        "/store/now-ginger-mint-comfort-tea.html",
        "/store/mhp-fit-lean-apple-cider-vinegar.html",
        "/store/force-factor-leanfire-acv-gummies.html",
        "/store/now-aloe-10000-probiotic.html",
        "/store/ovbi-pinks-superfood-and-immunity-blend.html",
        "/store/nutritox-apple-cider-vinegar.html",
        "/store/probiotic-defense.html",
        "/store/na-r-ala.html",
        "/store/orange-gutbac.html",
        "/store/now-womens-probiotic.html",
        "/store/mhp-fit-lean-collagen-probiotics.html",
        "/store/nutritox-gut-joy.html",
        "/store/now-activated-charcoal.html",
        "/store/8-billion-acidophilus-bifidus.html",
        "/store/proven-gut-health.html",
        "/store/fnx-rebalance.html",
        "/store/fnx-acv-gummies.html",
        "/store/myprotein-l-glutamine-amino-acid.html",
        "/store/swolverine-probiotix.html",
        "/store/stryve-bone-broth.html",
        "/store/now-gtf-chromium-200mcg.html",
        "/store/now-caprylic-acid.html",
        "/store/now-probiotic-10-50-billion.html",
        "/store/now-probiotic-10-25-billion.html",
        "/store/swolverine-acv-gummy.html",
        "/store/fnx-turmeric-gummies.html",
        "/store/now-probiotic-10-50-billion.html",
      ],
    },
    {
      title: "Heart Health",
      href: "https://www.muscleandstrength.com/store/category/general-health/heart-health.html",
      products: [
        "/store/core-fish-oil.html",
        "/store/omega-3.html",
        "/store/omega-3.html",
        "/store/omega-3.html",
        "/store/now-d-3-and-k-2.html",
        "/store/now-mega-d-3-and-mk-7.html",
        "/store/now-potassium-citrate.html",
        "/store/force-factor-total-beets-soft-chews.html",
        "/store/now-mk-7-vitamin-k-2-100mcg.html",
        "/store/now-b-12.html",
        "/store/ronniecoleman-omega-3-xs.html",
        "/store/force-factor-total-beets-energy-powder.html",
        "/store/now-coq10-softgels.html",
        "/store/now-foods-coq10.html",
        "/store/force-factor-total-beets-powder.html",
        "/store/swolverine-krill-oil.html",
        "/store/myprotein-omega-3.html",
        "/store/force-factor-nac.html",
        "/store/orange-healthiq.html",
        "/store/now-foods-coq10.html",
        "/store/natural-resveratrol.html",
        "/store/force-factor-total-beets-tablets.html",
        "/store/gaspari-nutrition-omega-3.html",
        "/store/now-coq10-with-omega-3.html",
        "/store/swolverine-coq10.html",
        "/store/red-omega.html",
        "/store/orange-beat.html",
        "/store/now-ultra-omega-3d.html",
        "/store/now-flax-oil.html",
        "/store/universal-nac.html",
        "/store/tri-3d-omega.html",
        "/store/now-indole-3-carbinol.html",
        "/store/clinical-cardio.html",
        "/store/now-coq10-softgels.html",
        "/store/total-beets-bp-support.html",
        "/store/natural-resveratrol.html",
        "/store/cod-liver-oil.html",
        "/store/finaflex-fish-oil.html",
        "/store/now-ubiquinol.html",
        "/store/now-coq10-softgels.html",
        "/store/now-flax-oil.html",
        "/store/now-coq10-with-omega-3.html",
        "/store/fnx-acv-gummies.html",
        "/store/now-ubiquinol.html",
        "/store/ronniecoleman-test-xs.html",
        "/store/core-fish-oil.html",
        "/store/ap-regimen-omega-3.html",
        "/store/now-coq10-softgels.html",
        "/store/gaspari-ageless-heart-health.html",
        "/store/now-foods-coq10.html",
        "/store/now-dha-500.html",
        "/store/now-red-yeast-rice-coq10.html",
        "/store/now-vitamin-b-6-100-mg.html",
        "/store/now-red-yeast-rice-coq10.html",
        "/store/cod-liver-oil.html",
        "/store/now-coq10-softgels.html",
      ],
    },
    {
      title: "Cholesterol Health",
      href: "https://www.muscleandstrength.com/store/category/general-health/cholesterol-health.html",
      products: [
        "/store/cla-core.html",
        "/store/tri-3d-omega.html",
        "/store/cla-core.html",
        "/store/glucomannan.html",
      ],
    },
    {
      title: "Eye & Vision",
      href: "https://www.muscleandstrength.com/store/category/general-health/eye-vision.html",
      products: [
        "/store/taurine-double-strength.html",
        "/store/now-vitamin-a.html",
        "/store/orange-healthiq.html",
        "/store/xp-sports-boost.html",
        "/store/now-lutein-zeaxanthin.html",
        "/store/man-sports-brainbridge.html",
        "/store/r1-player-1.html",
        "/store/now-lutein.html",
        "/store/now-double-strength-lutein.html",
        "/store/xp-sports-zero-lag.html",
        "/store/now-vitamin-a.html",
        "/store/now-clinical-strength-ocu-support.html",
        "/store/now-macular-vision.html",
        "/store/now-lutein.html",
        "/store/now-astaxanthin.html",
        "/store/xp-sports-gummies.html",
        "/store/taurine-double-strength.html",
        "/store/now-astaxanthin.html",
      ],
    },
    {
      title: "Skin Hair & Nails",
      href: "https://www.muscleandstrength.com/store/category/general-health/skin-hair-nails-health.html",
      products: [
        "/store/allmax-collagen-biotin-vitamin-c.html",
        "/store/orgain-collagen-peptides.html",
        "/store/321glo-collagen-cookie.html",
        "/store/nutrex-collagen.html",
        "/store/collagen-peptides-superfoods.html",
        "/store/usn-vibrance-weight-loss-collagen.html",
        "/store/321glo-collagen-brownie.html",
        "/store/ovbi-super-collagen-protein.html",
        "/store/321glo-collagen-brownie.html",
        "/store/usn-vibrance-weight-loss-collagen.html",
        "/store/collagen-types-1-and-3.html",
        "/store/alani-nu-balance-caps.html",
        "/store/biotin.html",
        "/store/bone-broth-athletic-collagen.html",
        "/store/collagen-types-1-and-3.html",
        "/store/obvi-collagenic-burn.html",
        "/store/321glo-collagen-cookie.html",
        "/store/now-biotin-10mg.html",
        "/store/usn-vibrance-collagen.html",
        "/store/orange-healthiq.html",
        "/store/yourganics-collagen.html",
        "/store/r1-collagen-peptides.html",
        "/store/nutritox-vibrance.html",
        "/store/ap-regimen-c3.html",
        "/store/biotin.html",
        "/store/obvi-beauty-sleep.html",
        "/store/swolverine-collagen.html",
        "/store/alpha-f.html",
        "/store/glaxon-wonder-collagen.html",
        "/store/now-uc-ii.html",
        "/store/stryve-collagen.html",
        "/store/nutritox-collagen-peptides.html",
        "/store/now-super-primrose.html",
        "/store/mhp-fit-lean-collagen-probiotics.html",
        "/store/r1-collagen-peptides.html",
        "/store/collagen-types-1-and-3.html",
        "/store/now-clinically-advanced-hair-skin-nails.html",
        "/store/fnx-resilience-collagen-protein.html",
        "/store/isopure-collagen.html",
        "/store/obvi-collagen-whey-protein.html",
        "/store/myprotein-hair-skin-nails-gummies.html",
        "/store/goli-superfruits-gummies.html",
        "/store/fnx-resilience-collagen-gummies.html",
        "/store/fnx-resilience-hair-gummies.html",
        "/store/ap-regimen-pure-collagen.html",
        "/store/h2obvi.html",
        "/store/motiv8-balance.html",
        "/store/now-evening-primrose-oil.html",
        "/store/now-hydration-rescue.html",
        "/store/now-aquatic-beauty.html",
        "/store/universal-nutrition-collagen.html",
        "/store/now-l-cysteine.html",
        "/store/now-super-primrose.html",
      ],
    },
  ],
};

export const clothingCategories = {
  title: "clothing",
  subCategories: [
    {
      title: "T-Shirts",
      href: "https://www.muscleandstrength.com/store/category/clothing/t-shirts.html",
      products: [
        "/store/mns-mens-seal-tee.html",
        "/store/mns-mens-seal-tee.html",
        "/store/spinal-tee.html",
        "/store/mns-mens-vintage-tee.html",
        "/store/mns-mens-vintage-tee.html",
        "/store/jnx-the-curse-tee.html",
        "/store/spinal-tee.html",
        "/store/jnx-the-curse-tee.html",
        "/store/mns-signature-tee.html",
        "/store/mns-mens-stamp-tee.html",
        "/store/ronnie-coleman-performance-tee.html",
        "/store/spinal-tee.html",
        "/store/worldwide-t-shirt.html",
        "/store/spinal-tee.html",
        "/store/yb-stamped-raglan.html",
        "/store/mns-mens-stamp-tee.html",
        "/store/bpi-all-or-nothing-v-neck.html",
        "/store/gat-compete-harder-t-shirt.html",
        "/store/mns-mens-stamp-tee.html",
        "/store/eflow-warrior-t-shirt.html",
        "/store/your-drive-our-fuel-t-shirt.html",
        "/store/muscletech-dumbbell-v-neck.html",
        "/store/primeval-labs-second-to-none-t-shirt.html",
        "/store/womens-yb-stamped-crop-top.html",
        "/store/m-s-hexagon-v-neck.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/swolverine-icon-tee.html",
        "/store/worldwide-t-shirt.html",
        "/store/mnc-weightplate-t-shirt.html",
        "/store/spinal-tee.html",
        "/store/muscle-and-strength-clothing-womens-crew-spinal.html",
        "/store/gasp-ops-edition-long-sleeve.html",
        "/store/gasp-relentless-skull-tee.html",
        "/store/muscle-beach-shark-crunch-t-shirt.html",
        "/store/muscle-beach-og-logo-t-shirt.html",
        "/store/muscle-beach-active-long-sleeve.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/gasp-ops-edition-long-sleeve.html",
        "/store/gasp-iron-tee.html",
        "/store/swolverine-icon-tee.html",
        "/store/swolverine-icon-tee.html",
        "/store/animal-iron-iconic-t-shirt.html",
        "/store/spinal-tee.html",
        "/store/worldwide-t-shirt.html",
        "/store/mgn-american-original-crew-neck-t-shirt.html",
        "/store/steal-the-show-t-shirt.html",
        "/store/jnx-vintage-jnx-tee.html",
        "/store/ronnie-coleman-university-tee.html",
      ],
    },
    {
      title: "Women's",
      href: "https://www.muscleandstrength.com/store/category/clothing/womens-clothing.html",
      products: [
        "/store/womens-yb-stamped-crop-top.html",
        "/store/mns-womens-vintage-cropped-tank.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/jnx-cross-back-tank.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/muscle-and-strength-clothing-womens-crew-spinal.html",
        "/store/jnx-compression-shorts.html",
        "/store/ps-sports-bra-and-shorts.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/muscle-and-strength-clothing-ladies-seal-tank.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/jnx-cropped-zip-hoodie.html",
        "/store/jnx-compression-leggings.html",
        "/store/nla-tank-rewards.html",
        "/store/ps-crop-top.html",
        "/store/ps-crop-top.html",
        "/store/ps-crop-top.html",
        "/store/womens-university-crop-top.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/muscle-and-strength-clothing-womens-spinal-burnout-tank.html",
        "/store/jnx-compression-top.html",
        "/store/bb-womens-regular-tee.html",
        "/store/bb-womens-regular-tee.html",
        "/store/bb-womens-regular-tee.html",
      ],
    },
    {
      title: "Sleeveless",
      href: "https://www.muscleandstrength.com/store/category/clothing/sleeveless.html",
      products: [
        "/store/jnx-asymmetrical-sleeveless-hoodie.html",
        "/store/gasp-vintage-tback-tank.html",
        "/store/ps-athlete-tank.html",
      ],
    },
    {
      title: "Tanks & Stringers",
      href: "https://www.muscleandstrength.com/store/category/clothing/muscle-shirts-tanks.html",
      products: [
        "/store/mns-mens-stringer-tank.html",
        "/store/jnx-the-curse-stringer.html",
        "/store/mns-mens-stamp-tank.html",
        "/store/jnx-the-curse-tank.html",
        "/store/mns-mens-stamp-tank.html",
        "/store/mns-womens-vintage-cropped-tank.html",
        "/store/jnx-the-curse-tank.html",
        "/store/jnx-cross-back-tank.html",
        "/store/jnx-the-curse-stringer.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/muscle-and-strength-clothing-ladies-seal-tank.html",
        "/store/nla-tank-rewards.html",
        "/store/gasp-ribbed-t-back.html",
        "/store/muscle-beach-og-logo-tank-top.html",
        "/store/muscle-beach-og-logo-tank-top.html",
        "/store/muscle-beach-og-logo-tank-top.html",
        "/store/gasp-vintage-tback-tank.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/mns-mens-stringer-tank.html",
        "/store/ps-athlete-tank.html",
        "/store/ps-spinal-stringer.html",
        "/store/muscle-and-strength-clothing-womens-spinal-burnout-tank.html",
        "/store/gasp-ribbed-t-back.html",
      ],
    },
    {
      title: "Shorts",
      href: "https://www.muscleandstrength.com/store/category/clothing/shorts.html",
      products: [
        "/store/jnx-compression-shorts.html",
        "/store/ps-sports-bra-and-shorts.html",
        "/store/gasp-pro-mesh-shorts.html",
        "/store/gasp-pro-mesh-shorts.html",
        "/store/gasp-pro-shorts.html",
        "/store/gasp-pro-shorts.html",
      ],
    },
    {
      title: "Muscle & Strength Clothing",
      href: "https://www.muscleandstrength.com/store/category/clothing/mands.html",
      products: [
        "/store/mns-mens-seal-tee.html",
        "/store/mns-mens-seal-tee.html",
        "/store/spinal-tee.html",
        "/store/mns-mens-vintage-tee.html",
        "/store/mns-mens-vintage-tee.html",
        "/store/spinal-tee.html",
        "/store/mns-signature-tee.html",
        "/store/mns-mens-stamp-tee.html",
        "/store/mns-mens-stringer-tank.html",
        "/store/spinal-tee.html",
        "/store/worldwide-t-shirt.html",
        "/store/spinal-tee.html",
        "/store/mns-mens-stamp-tee.html",
        "/store/mns-mens-stamp-tee.html",
        "/store/mns-mens-stamp-tank.html",
        "/store/mns-mens-stamp-tank.html",
        "/store/m-and-s-spinal-hoodie.html",
        "/store/mns-womens-vintage-cropped-tank.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/worldwide-t-shirt.html",
        "/store/spinal-tee.html",
        "/store/muscle-and-strength-clothing-womens-crew-spinal.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/mns-womens-stamp-cropped-tee.html",
        "/store/spinal-tee.html",
        "/store/worldwide-t-shirt.html",
        "/store/mns-womens-seal-cropped-tank.html",
        "/store/mns-mens-stringer-tank.html",
        "/store/m-and-s-spinal-hoodie.html",
      ],
    },
    {
      title: "Hats & Headgear",
      href: "https://www.muscleandstrength.com/store/category/clothing/headgear.html",
      products: [
        "/store/animal-beanie.html",
        "/store/jnx-the-curse-flatbill-snapback-cap.html",
        "/store/jnx-the-curse-neck-gaiter.html",
        "/store/jnx-flatbill-snapback-cap.html",
        "/store/prosupps-trucker-hat.html",
        "/store/prosupps-trucker-hat.html",
        "/store/on-flexfit-promo-hat.html",
      ],
    },
    {
      title: "Hoodies & Sweatshirts",
      href: "https://www.muscleandstrength.com/store/category/clothing/hoodies.html",
      products: [
        "/store/rcss-university-hoodie.html",
        "/store/m-and-s-spinal-hoodie.html",
        "/store/jnx-performance-hoodie.html",
        "/store/jnx-asymmetrical-sleeveless-hoodie.html",
        "/store/rcss-8x-world-champion-hoodie.html",
        "/store/rcss-legacy-windbreaker.html",
        "/store/jnx-winter-hoodie.html",
        "/store/jnx-cropped-zip-hoodie.html",
        "/store/gasp-thermal-gym-sweater.html",
        "/store/gasp-thermal-hoodie.html",
        "/store/gasp-thermal-hoodie.html",
        "/store/rcss-yeah-buddy-stamped-hoodie.html",
        "/store/ps-baseball-tee.html",
        "/store/m-and-s-spinal-hoodie.html",
        "/store/ps-hooded-tee.html",
        "/store/ps-hooded-tee.html",
        "/store/gasp-thermal-hoodie.html",
        "/store/bb-graphic-hoodie.html",
      ],
    },
    {
      title: "Pants",
      href: "https://www.muscleandstrength.com/store/category/clothing/pants.html",
      products: [
        "/store/bb-tapered-joggers-v2.html",
        "/store/bb-no-89-mesh-pant.html",
        "/store/bb-tapered-joggers-v2.html",
        "/store/bb-no-89-mesh-pant.html",
        "/store/gasp-original-mesh-pants.html",
        "/store/gasp-original-mesh-pants.html",
        "/store/jnx-compression-leggings.html",
        "/store/gasp-vintage-sweatpants.html",
        "/store/gasp-vintage-sweatpants.html",
      ],
    },
  ],
}
;
export const functionalFoodsCategories = {
  title: "functional-foods",
  subCategories: [
    {
      title: "Protein Bars",
      href: "https://www.muscleandstrength.com/store/category/functional-foods/protein-bars.html",
      products: [
        "/store/r1-bar1.html",
        "/store/allmax-protein-snackbar.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/primebites-protein-brownies.html",
        "/store/barebells-protein-bar.html",
        "/store/r1-bar1-smooth.html",
        "/store/barebells-protein-bar.html",
        "/store/authentic-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/allmax-protein-snackbar.html",
        "/store/barebells-protein-bar.html",
        "/store/authentic-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/quest-bar.html",
        "/store/authentic-bar.html",
        "/store/sinfit-crunch-bar.html",
        "/store/sinfit-plant-based-crunch-bar.html",
        "/store/mp-combat-crunch-bars.html",
        "/store/primebites-protein-brownies.html",
        "/store/r1-bar1-smooth.html",
        "/store/bsn-syntha-6-protein-crisp-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/gaspari-ageless-collagen-protein-bars.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/quest-hero-bar.html",
        "/store/obvi-bar.html",
        "/store/myprotein-vegan-protein-bar.html",
        "/store/quest-snack-bar.html",
        "/store/grenade-carb-killa-bars.html",
        "/store/animal-pro-bar.html",
        "/store/myprotein-triple-stack-bars.html",
        "/store/layered-bar.html",
        "/store/sinfit-crunch-bar.html",
        "/store/mp-combat-crunch-bars.html",
        "/store/myprotein-nuts-bar.html",
        "/store/obvi-bar.html",
        "/store/bsn-syntha-6-protein-crisp-bar.html",
        "/store/grenade-carb-killa-bars.html",
        "/store/layered-bar.html",
        "/store/myprotein-triple-stack-bars.html",
        "/store/r1-bar1.html",
        "/store/quest-bar.html",
      ],
    },
    {
      title: "High Protein Snacks",
      href: "https://www.muscleandstrength.com/store/category/functional-foods/high-protein-snacks.html",
      products: [
        "/store/stryve-biltong-stick.html",
        "/store/tasty-pastry.html",
        "/store/321glo-collagen-cookie.html",
        "/store/primebites-protein-brownies.html",
        "/store/321glo-collagen-brownie.html",
        "/store/crunchy-broad-beans.html",
        "/store/powerful-oatmeal.html",
        "/store/321glo-collagen-brownie.html",
        "/store/stryve-biltong.html",
        "/store/tasty-pastry.html",
        "/store/on-protein-wafers.html",
        "/store/321glo-collagen-cookie.html",
        "/store/eat-me-guilt-free-brownie.html",
        "/store/finaflex-oatmeal-protein-pie.html",
        "/store/powerful-oatmeal.html",
        "/store/powerful-oatmeal-value-pack.html",
        "/store/on-protein-wafers.html",
        "/store/allmax-hexapro-protein-popcorn.html",
        "/store/sinfit-waffle.html",
        "/store/vacadillos-carne-seca.html",
        "/store/mpb-cookie-bites.html",
        "/store/complete-cookie.html",
        "/store/powerful-overnight-oats.html",
        "/store/primebites-protein-brownies.html",
        "/store/complete-cookie.html",
        "/store/stryve-biltong-stick.html",
        "/store/myprotein-brownie.html",
        "/store/on-protein-almonds.html",
        "/store/sinfit-cookies.html",
        "/store/myprotein-protein-wafers.html",
        "/store/mpb-keto-cookie-bites.html",
        "/store/beef-biltong.html",
        "/store/now-raw-macadamia-nuts.html",
        "/store/sinfit-spread.html",
        "/store/sinfit-spread.html",
        "/store/now-almonds.html",
        "/store/protein-puffs.html",
        "/store/beef-biltong.html",
        "/store/now-cashews.html",
        "/store/now-cashews.html",
        "/store/now-mango-bites.html",
        "/store/now-almonds.html",
        "/store/now-goldenberries.html",
        "/store/sinfit-pancake.html",
        "/store/rcss-king-cake.html",
        "/store/protein-puffs.html",
        "/store/myprotein-nuts-bar.html",
        "/store/sinfit-peanut-powder.html",
      ],
    },
    {
      title: "Baking & Cooking",
      href: "https://www.muscleandstrength.com/store/category/functional-foods/baking-cooking.html",
      products: [
        "/store/sinfit-seasonings.html",
        "/store/now-organic-maple-syrup.html",
        "/store/now-organic-monk-fruit-liquid.html",
        "/store/now-erythritol.html",
        "/store/sinfit-waffle.html",
        "/store/r1-easy-protein-omelet.html",
        "/store/r1-wheycakes.html",
        "/store/now-better-stevia-liquid.html",
        "/store/sinfit-syrup.html",
        "/store/now-organic-hemp-seed-hearts.html",
        "/store/now-organic-monk-fruit-liquid.html",
        "/store/now-organic-quinoa-penne.html",
        "/store/now-organic-quinoa-macaroni.html",
        "/store/now-better-stevia-organic-extract-powder.html",
        "/store/finaflex-opp-vegan-drink-mix.html",
        "/store/now-manuka-honey.html",
        "/store/now-organic-monk-fruit-liquid.html",
        "/store/now-coconut-milk-powder.html",
        "/store/grenade-carb-killa-protein-spread.html",
        "/store/now-dry-roasted-macadamia-nuts.html",
        "/store/now-raw-macadamia-nuts.html",
        "/store/sinfit-spread.html",
        "/store/sinfit-spread.html",
        "/store/now-almonds.html",
        "/store/now-beef-gelatin-powder.html",
        "/store/now-cashews.html",
        "/store/now-cashews.html",
        "/store/now-mango-bites.html",
        "/store/now-almonds.html",
        "/store/now-cocoa-powder.html",
        "/store/now-goldenberries.html",
        "/store/now-organic-monk-fruit-powder.html",
        "/store/sinfit-pancake.html",
        "/store/sinfit-peanut-powder.html",
        "/store/now-organic-quinoa-spaghetti.html",
        "/store/now-sunflower-seeds.html",
        "/store/now-sunflower-seeds.html",
        "/store/now-ginger-slices.html",
        "/store/now-organic-raw-cacao-powder.html",
        "/store/now-sunflower-seeds.html",
        "/store/now-organic-monk-fruit-powder.html",
        "/store/now-better-stevia-liquid-french-vanilla.html",
        "/store/now-organic-popcorn.html",
        "/store/now-better-stevia-liquid.html",
        "/store/now-almond-flour.html",
        "/store/now-organic-milled-white-chia-seeds.html",
      ],
    },
  ],
};
