export const topDealsProductsData = [
  {
    href: "/store/perfect-sports-apex-grass-fed-whey-protein.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/e7aba0/240/0/apex_whey_5lbs_chocolate_ice_cream.jpg",
    title: "PERFECT Sports APEX Grass-Fed, 5lbs",
    deal: "LIMITED TIME PRICE CUT",
    price: 49.99,
  },
  {
    href: "/store/nitro-tech-100-whey-gold.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/fac6e7/240/0/whey_gold_5lb_double_rich_chocolate.jpg",
    title: "MuscleTech Nitro-Tech 100% Whey Gold, 5lbs",
    deal: "EXTRA 30% OFF",
    price: 45.49,
  },
  {
    href: "/store/primeval-labs-eaa-max-energy.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/5a2836/240/0/island_punch_front_3_3.jpg",
    title: "Primeval Labs EAA MAX ENERGY, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/vitaform.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/6793a5/240/0/vitaform-60-tabs.jpg",
    title: "Allmax Vitaform, 60 Tablets",
    deal: "Buy 1 Get 1 FREE",
    price: 19.99,
  },
  {
    href: "/store/r1-creatine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/f6c717/240/0/rule1__creatine_30ser_new.jpg",
    title: "Rule 1 R1 Creatine, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/musclepharm-bcaa-powder.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/c05dd3/240/0/mpe_bcaa_30serv_watermelon_1_2.jpg",
    title: "MP Essentials BCAA, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 24.99,
  },
  {
    href: "/store/omega-3.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/b1dcf0/240/0/now_omega-3_1_2.jpg",
    title: "NOW Foods Omega-3, 200 Softgels",
    deal: "Buy 1 Get 1 FREE",
    price: 17.99,
  },
  {
    href: "/store/lipo-6-black-uc.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/98c306/240/0/lipo6blackucbox17_1_16.jpg",
    title: "Nutrex Lipo-6 Black UC, 60 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/c4-g4.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/f2247e/240/0/c4_original_30serv_cl_1.jpg",
    title: "Cellucor C4, 30 Servings",
    deal: "Buy 2 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/ripper.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/06bad4/240/0/the-ripper-blood-orange-30-serve.jpg",
    title: "JNX Sports The Ripper, 30 Servings",
    deal: "LIMITED TIME PRICE CUT",
    price: 17.99,
  },
  {
    href: "/store/force-factor-probioslim.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/57c857/240/0/probioslim30ct_bottlerender.jpg",
    title: "Force Factor ProbioSlim, 30 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 17.99,
  },
  {
    href: "/store/bpi-best-bcaa.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/c8573f/240/0/best_bcaa_30_servs_-arctic_ice-new_1_2.jpg",
    title: "BPI Best BCAA, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 27.99,
  },
];

export const topRatedProductsData = [
  {
    href: "/store/nitro-tech-performance.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/590990/240/0/nitro_tech_whey_protein_4lbs_vanilla.jpg",
    title: "MuscleTech Nitro-Tech Protein, 4lbs",
    deal: "EXTRA 30% OFF",
    price: 41.99,
  },
  {
    href: "/store/musclepharm-combat-100-whey-protein.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/0e6ad6/240/0/mp_100_combat_whey_small_1_1_1_3.jpg",
    title: "MP Combat 100% Whey, 5lbs",
    deal: "LIMITED TIME PRICE CUT",
    price: 49.99,
  },
  {
    href: "/store/scivation-xtend.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/0dc9a7/240/0/glacial_grape_-_xtend_30_9.jpg",
    title: "Scivation XTend, 30 Servings",
    deal: "30% DISCOUNT IN CART",
    price: 36.99,
  },
  {
    href: "/store/primeval-labs-apeshit-cutz.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/210f7a/240/0/apesh-t-cutz-smashberry.jpg",
    title: "Primeval Labs APESH*T Cutz, 50 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/test-x180.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/969da8/240/0/testx18060ct_bottlerender.jpg",
    title: "Force Factor Test X180, 60 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 34.99,
  },
  {
    href: "/store/r1-lbs.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/542817/240/0/R1_LBS_10_Choc_2.jpg",
    title: "Rule 1 R1 LBS, 6lbs",
    deal: "Buy 1 Get 1 FREE",
    price: 53.99,
  },
  {
    href: "/store/man-sports-scorch-powder.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/7b82b5/240/0/scorch-powder-75sv-peach-rings.jpg",
    title: "MAN Sports Scorch, 75 Serving",
    deal: "30% DISCOUNT IN CART",
    price: 29.99,
  },
  {
    href: "/store/isoflex.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/2811eb/240/0/isoflex_2lb-chocmint_20160209155609-sm_1_1.jpg",
    title: "AllMAX IsoFlex, 2lbs",
    deal: "Buy 2 for $69.99",
    price: 49.99,
  },
  {
    href: "/store/rcss-yeah-buddy.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/6ca250/240/0/YB_30srv_MP_1000_1.jpg",
    title: "RCSS Yeah Buddy, 30 Servings",
    deal: "PRICE CUT + FREE BETA-ALANINE 50ct",
    price: 24.99,
  },
  {
    href: "/store/bpi-sports-cla-plus-carnitine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/be10f2/240/0/cla_carnitine_-_50_servs_-_fruit_punch-new_1_10.jpg",
    title: "BPI CLA + Carnitine, 50 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 32.99,
  },
  {
    href: "/store/usn-bcaa-amino-plus-powder.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/1a8374/240/0/bcaa_amino_30_servings_greenapple.jpg",
    title: "USN BCAA Amino+, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 28.99,
  },
  {
    href: "/store/perfect-sports-diesel-whey-protein-isolate.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/c2d0d4/240/0/diesel_2lbs_milk_chocolate.jpg",
    title: "PERFECT Sports DIESEL, 2lbs",
    deal: "Buy 2 Get 1 FREE",
    price: 49.99,
  },
];

export const trendingProductsData = [
  {
    href: "/store/primeval-labs-apeshit.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/94e960/240/0/apesh-t-untamed-smashberry_1.jpg",
    title: "Primeval Labs APESH*T, 40 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 29.99,
  },
  {
    href: "/store/nutrex-lipo-6-defining-gel.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/5ed3e3/240/0/lipo6defgel.jpg",
    title: "Nutrex Lipo-6 Defining Gel, 4oz",
    deal: "Buy 1 Get 1 FREE",
    price: 34.97,
  },
  {
    href: "/store/acuts.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/b3c3c9/240/0/acuts_large_5.jpg",
    title: "AllMax AminoCuts, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 21.99,
  },
  {
    href: "/store/muscletech-cell-tech-hardcore.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/52c730/240/0/masstech_elite_7lbs_vanilla_cake.jpg",
    title: "MuscleTech Cell-Tech, 6lbs",
    deal: "EXTRA 30% OFF",
    price: 41.99,
  },
  {
    href: "/store/nutrex-isofit.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/625202/240/0/isofit-chocolate-shake-5lbs.jpg",
    title: "Nutrex ISOFIT, 5lbs",
    deal: "LIMITED TIME PRICE CUT",
    price: 59.99,
  },
  {
    href: "/store/iso-amino.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/7eebba/240/0/ISO-Amino-BB-0-STR_3.jpg",
    title: "MAN Sports ISO-Amino, 30 Servings",
    deal: "LIMITED TIME PRICE CUT",
    price: 14.99,
  },
  {
    href: "/store/r1-charged-creatine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/5ecb43/240/0/30_servings_blue_razz_lemonade_1.jpg",
    title: "Rule 1 Charged Creatine, 30 Servings",
    deal: "Buy 2 for $39.99",
    price: 33.99,
  },
  {
    href: "/store/now-nac-1000mg-tablets.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/9dc530/240/0/nac_1000mg_120_tablets.jpg",
    title: "NOW Foods NAC 1000mg, 120 Tabs",
    deal: "LIMITED TIME PRICE CUT",
    price: 15.99,
  },
  {
    href: "/store/cobra-labs-curse.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/3bfc25/240/0/the-curse-lemon-rush-50-serve.jpg",
    title: "JNX Sports The Curse, 50 Servings",
    deal: "LIMITED TIME PRICE CUT",
    price: 19.99,
  },
  {
    href: "/store/usn-phedracut-water-x-diuretic.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/39e504/240/0/phedracut_waterx_new_look_1.jpg",
    title: "USN PhedraCut Water X, 90 Capsules",
    deal: "Buy 1 Get 1 FREE",
    price: 14.99,
  },
  {
    href: "/store/rcss-l-carnitine.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/1960d2/240/0/l-carnitine-xs-3000-blue-razz.jpg",
    title: "RCSS L-Carnitine 3000, 31 Servings",
    deal: "BOGO + FREE Fizzique RTD",
    price: 34.99,
  },
  {
    href: "/store/perfect-sports-iprep.html",
    imgUrl:
      "https://cdn.muscleandstrength.com/store/media/mnsresized/promos/d005b3/240/0/iprep-orange-gummy-bear--us.jpg",
    title: "PERFECT Sports iPrep, 30 Servings",
    deal: "Buy 1 Get 1 FREE",
    price: 24.99,
  },
];

export const proteinCategories = {
  bannerData: {
    href: "/store/brands/allmax",
    isSale: false,
    srcset:
      "https://cdn.muscleandstrength.com/store/media/merchandising/2_21_Allmax_BP_Mobile_1.jpg",
    media: "(max-width: 839px)",
    src: "https://cdn.muscleandstrength.com/store/media/merchandising/2_21_Allmax_BP_Desktop_1.jpg",
    alt: "Demand More, Get Allmax - The trusted brand of athletes and fitness enthusiasts on sale now",
  },
  title: "protein",
  subCategories: [
    {
      title: "Whey Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein.html",
      products: [
        "/store/bpi-whey-hd.html",
        "/store/six-star-100-whey-protein-plus.html",
        "/store/nitro-tech-100-whey-gold.html",
        "/store/nitro-tech-performance.html",
        "/store/musclepharm-combat-100-whey-protein.html",
        "/store/bpi-best-protein.html",
        "/store/nitro-tech-performance.html",
        "/store/dymatize-iso-100.html",
        "/store/nitro-tech-ripped.html",
        "/store/isoflex.html",
        "/store/nitro-tech-performance.html",
        "/store/bpisports-isohd-whey-protein.html",
        "/store/allmax-allwhey-gold.html",
        "/store/100-whey-gold-standard.html",
        "/store/perfect-sports-apex-grass-fed-whey-protein.html",
        "/store/100-whey-gold-standard.html",
        "/store/nitro-tech-100-whey-gold.html",
        "/store/dymatize-iso-100.html",
        "/store/allmax-allwhey-classic.html",
        "/store/isoflex.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/r1-lbs.html",
        "/store/r1-whey-blend.html",
        "/store/nitro-tech-ripped.html",
        "/store/impact-whey.html",
        "/store/allmax-allwhey-gold.html",
        "/store/muscletech-grass-fed-whey.html",
        "/store/rcss-king-whey.html",
        "/store/nitro-tech-performance.html",
        "/store/isonatural.html",
        "/store/muscle-gauge-whey-protein-isolate.html",
        "/store/impact-whey-isolate.html",
        "/store/syntha-6.html",
        "/store/impact-whey.html",
        "/store/elite-whey-protein.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/r1-whey-blend.html",
        "/store/premier-protein-100percent-whey.html",
        "/store/cor-performance-whey.html",
        "/store/platinum-hydrowhey.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/r1-whey-blend.html",
        "/store/impact-whey-isolate.html",
        "/store/isopure.html",
        "/store/allmax-allwhey-classic.html",
        "/store/rivalus-rival-whey.html",
        "/store/isonatural.html",
        "/store/syntha-6.html",
        "/store/rivalus-promasil.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/six-star-whey-isolate.html",
        "/store/isoflex.html",
      ],
    },
    {
      title: "Vegan Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/vegan-protein-supplements.html",
      products: [
        "/store/barebells-plant-based-protein-bar.html",
        "/store/orgain-organic-protein.html",
        "/store/orgain-organic-meal.html",
        "/store/orgain-organic-protein.html",
        "/store/bpi-sports-veggie-protein.html",
        "/store/orgain-organic-protein-superfoods.html",
        "/store/vegan-organic-nutrition-shake.html",
        "/store/nutrex-plant-protein.html",
        "/store/orgain-organic-protein-superfoods.html",
        "/store/raw-fusion.html",
        "/store/purely-inspired-organic-protein.html",
        "/store/vegan-joy.html",
        "/store/orgain-organic-protein.html",
        "/store/keto-plant-protein.html",
        "/store/complete-plant-protein.html",
        "/store/orgain-sport-protein.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/perfect-sports-diesel-vegan.html",
        "/store/mhp-fit-lean-plant-protein.html",
        "/store/now-plant-protein-complex.html",
        "/store/powerful-plant-based-protein-shake.html",
        "/store/now-soy-protein-isolate.html",
        "/store/orgain-sport-protein.html",
        "/store/raw-fusion.html",
        "/store/gaspari-proven-vegan-protein.html",
        "/store/sinfit-plant-based-crunch-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/r1-plant-protein.html",
        "/store/swolverine-plant-protein.html",
        "/store/simple-protein.html",
        "/store/fnx-reform.html",
        "/store/raw-fusion.html",
        "/store/complete-cookie.html",
        "/store/vegan-protein.html",
        "/store/powerful-plant-based-protein-shake.html",
        "/store/orgain-organic-protein-greens.html",
        "/store/100-plant-protein.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/v-pro.html",
        "/store/prosupps-plant-perform.html",
        "/store/finaflex-opp-vegan-drink-mix.html",
        "/store/complete-cookie.html",
        "/store/myprotein-vegan-protein-bar.html",
        "/store/r1-plant-protein-energy.html",
        "/store/v-pro.html",
        "/store/now-organic-pumpkin-seed-protein.html",
        "/store/perfect-sports-diesel-vegan.html",
        "/store/orgain-organic-protein.html",
        "/store/vegan-protein.html",
      ],
    },
    {
      title: "Protein Bars",
      href: "https://www.muscleandstrength.com/store/category/protein/bars.html",
      products: [
        "/store/r1-bar1.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/allmax-protein-snackbar.html",
        "/store/barebells-protein-bar.html",
        "/store/r1-bar1-smooth.html",
        "/store/barebells-protein-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/primebites-protein-brownies.html",
        "/store/authentic-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/authentic-bar.html",
        "/store/allmax-protein-snackbar.html",
        "/store/on-protein-wafers.html",
        "/store/primebites-protein-brownies.html",
        "/store/quest-bar.html",
        "/store/authentic-bar.html",
        "/store/gaspari-ageless-collagen-protein-bars.html",
        "/store/on-protein-wafers.html",
        "/store/sinfit-crunch-bar.html",
        "/store/sinfit-plant-based-crunch-bar.html",
        "/store/orgain-organic-protein-snack-bar.html",
        "/store/mp-combat-crunch-bars.html",
        "/store/r1-bar1-smooth.html",
        "/store/bsn-syntha-6-protein-crisp-bar.html",
        "/store/barebells-protein-bar.html",
        "/store/mp-combat-crunch-bars.html",
        "/store/bsn-syntha-6-protein-crisp-bar.html",
        "/store/grenade-carb-killa-bars.html",
        "/store/layered-bar.html",
        "/store/rcss-king-cake.html",
        "/store/myprotein-triple-stack-bars.html",
        "/store/quest-bar.html",
        "/store/obvi-bar.html",
        "/store/r1-bar1.html",
        "/store/barebells-plant-based-protein-bar.html",
        "/store/quest-hero-bar.html",
        "/store/obvi-bar.html",
        "/store/myprotein-vegan-protein-bar.html",
        "/store/quest-snack-bar.html",
        "/store/grenade-carb-killa-bars.html",
        "/store/animal-pro-bar.html",
        "/store/myprotein-triple-stack-bars.html",
        "/store/layered-bar.html",
        "/store/sinfit-crunch-bar.html",
      ],
    },
    {
      title: "Whey Protein Isolate",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein-isolate.html",
      products: [
        "/store/dymatize-iso-100.html",
        "/store/isoflex.html",
        "/store/perfect-sports-diesel-whey-protein-isolate.html",
        "/store/bpisports-isohd-whey-protein.html",
        "/store/man-sports-isolate-protein-powder.html",
        "/store/dymatize-iso-100.html",
        "/store/isoflex.html",
        "/store/fizzique-sparkling-protein-water.html",
        "/store/nutrex-isofit.html",
        "/store/impact-clear-whey-isolate.html",
        "/store/muscletech-iso-whey-clear-protein.html",
        "/store/usn-zero-carb-isopro-whey-protein-isolate.html",
        "/store/isonatural.html",
        "/store/muscle-gauge-whey-protein-isolate.html",
        "/store/impact-whey-isolate.html",
        "/store/fizzique-sparkling-protein-water.html",
        "/store/r1-protein.html",
        "/store/now-whey-protein-isolate.html",
        "/store/swolverine-whey-protein-isolate.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/nutrex-isofit.html",
        "/store/gold-standard-100-whey-isolate.html",
        "/store/platinum-hydrowhey.html",
        "/store/impact-whey-isolate.html",
        "/store/isopure.html",
        "/store/magnum-quattro.html",
        "/store/r1-protein.html",
        "/store/magnum-quattro.html",
        "/store/now-whey-protein-isolate.html",
        "/store/xtend-pro.html",
        "/store/xtend-pro.html",
        "/store/isonatural.html",
        "/store/usn-zero-carb-isopro-whey-protein-isolate.html",
        "/store/perfect-sports-diesel-whey-protein-isolate.html",
        "/store/now-whey-protein-isolate.html",
        "/store/r1-protein.html",
        "/store/six-star-whey-isolate.html",
        "/store/isoflex.html",
        "/store/isopure.html",
        "/store/iso-tropic-max.html",
        "/store/primeval-labs-isolit.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/magnum-quattro.html",
        "/store/muscle-gauge-whey-protein-isolate.html",
        "/store/magnum-quattro.html",
        "/store/perfect-sports-perfect-whey-concentrate.html",
        "/store/isopure.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
      ],
    },
    {
      title: "Whey Protein Blends",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein-blends.html",
      products: [
        "/store/nitro-tech-100-whey-gold.html",
        "/store/nitro-tech-performance.html",
        "/store/nitro-tech-performance.html",
        "/store/nitro-tech-ripped.html",
        "/store/nitro-tech-performance.html",
        "/store/allmax-allwhey-gold.html",
        "/store/100-whey-gold-standard.html",
        "/store/bpi-whey-hd.html",
        "/store/100-whey-gold-standard.html",
        "/store/nitro-tech-100-whey-gold.html",
        "/store/allmax-allwhey-classic.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/r1-lbs.html",
        "/store/r1-whey-blend.html",
        "/store/nitro-tech-ripped.html",
        "/store/allmax-allwhey-gold.html",
        "/store/nitro-tech-performance.html",
        "/store/syntha-6.html",
        "/store/elite-whey-protein.html",
        "/store/r1-whey-blend.html",
        "/store/cor-performance-whey.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/r1-whey-blend.html",
        "/store/usn-premium-100-whey-protein-plus.html",
        "/store/magnum-quattro.html",
        "/store/allmax-allwhey-classic.html",
        "/store/magnum-quattro.html",
        "/store/rivalus-promasil.html",
        "/store/rivalus-rival-whey.html",
        "/store/syntha-6.html",
        "/store/usn-blue-lab-100-whey-protein.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/magnum-quattro.html",
        "/store/magnum-quattro.html",
        "/store/syntha-6.html",
        "/store/fnx-restart.html",
        "/store/core-nutritionals-mrp.html",
        "/store/rivalus-rival-whey.html",
        "/store/rivalus-rival-whey.html",
        "/store/elite-whey-protein.html",
        "/store/fnx-refuel.html",
        "/store/gaspari-myofusion-advanced.html",
        "/store/r1-lbs.html",
        "/store/ovbi-kids-complete-protein.html",
        "/store/natural-whey.html",
        "/store/promore.html",
        "/store/gaspari-myofusion-advanced.html",
      ],
    },
    {
      title: "Multi-Protein Blends",
      href: "https://www.muscleandstrength.com/store/category/protein/protein-blends.html",
      products: [
        "/store/combat-powder.html",
        "/store/combat-powder.html",
        "/store/phase8.html",
        "/store/hexapro.html",
        "/store/hexapro.html",
        "/store/raw-fusion.html",
        "/store/primebites-protein-brownies.html",
        "/store/organic-nutrition-shake.html",
        "/store/pro-antium.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/powerful-protein-shake.html",
        "/store/usn-premium-100-whey-protein-plus.html",
        "/store/kids-protein-shake.html",
        "/store/mhp-probolic-sr.html",
        "/store/rivalus-promasil.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/mhp-probolic-sr.html",
        "/store/raw-fusion.html",
        "/store/rivalus-promasil.html",
        "/store/primebites-protein-brownies.html",
        "/store/syntha-6-isolate.html",
        "/store/core-nutritionals-mrp.html",
        "/store/syntha-6-isolate.html",
        "/store/powerful-protein-shake.html",
        "/store/beast-protein.html",
        "/store/raw-fusion.html",
        "/store/real-carbs-plus-protein.html",
        "/store/powerful-protein-shake.html",
        "/store/combat-powder.html",
        "/store/delight.html",
        "/store/sinfit-peanut-powder.html",
        "/store/clean-protein-shake.html",
        "/store/combat-powder.html",
      ],
    },
    {
      title: "Casein Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/casein-protein.html",
      products: [
        "/store/elite-series-casein-protein.html",
        "/store/r1-casein.html",
        "/store/100-casein-protein.html",
        "/store/r1-casein.html",
        "/store/elite-casein.html",
        "/store/casein-fx.html",
        "/store/elite-casein.html",
        "/store/100-casein-protein.html",
        "/store/core-nutritionals-mrp.html",
        "/store/natural-100-casein-gold-standard.html",
        "/store/fnx-retire.html",
        "/store/musclepharm-combat-casein.html",
        "/store/natural-100-casein-gold-standard.html",
      ],
    },
    {
      title: "Extended Release Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/extended-release-protein.html",
      products: [
        "/store/combat-powder.html",
        "/store/combat-powder.html",
        "/store/phase8.html",
        "/store/syntha-6.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/usn-premium-100-whey-protein-plus.html",
        "/store/mhp-probolic-sr.html",
        "/store/syntha-6.html",
        "/store/bsn-syntha-6-edge.html",
        "/store/mhp-probolic-sr.html",
        "/store/syntha-6.html",
        "/store/syntha-6-isolate.html",
        "/store/syntha-6-isolate.html",
        "/store/beast-protein.html",
        "/store/combat-powder.html",
        "/store/combat-powder.html",
      ],
    },
    {
      title: "Naturally Flavored Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/naturally-flavored-protein.html",
      products: [
        "/store/keto-plant-protein.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/now-soy-protein-isolate.html",
        "/store/natural-100-whey-gold-standard.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/natural-whey.html",
        "/store/vegan-protein.html",
        "/store/100-plant-protein.html",
        "/store/natural-100-casein-gold-standard.html",
        "/store/natural-isolate.html",
        "/store/orgain-grass-fed-whey.html",
        "/store/natural-whey.html",
        "/store/natural-100-casein-gold-standard.html",
        "/store/natural-isopure.html",
        "/store/natural-isolate.html",
        "/store/vegan-protein.html",
        "/store/simple-protein.html",
        "/store/isopure.html",
        "/store/clean-protein-shake.html",
      ],
    },
    {
      title: "Whey Protein Hydrolysate",
      href: "https://www.muscleandstrength.com/store/category/protein/whey-protein-hydrolysate.html",
      products: [
        "/store/bpisports-isohd-whey-protein.html",
        "/store/r1-protein.html",
        "/store/platinum-hydrowhey.html",
        "/store/r1-protein.html",
        "/store/r1-protein.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/r1-protein-isolate-naturally-flavored.html",
        "/store/platinum-hydrowhey.html",
        "/store/gaspari-nutrition-proven-whey.html",
        "/store/gaspari-nutrition-proven-whey.html",
      ],
    },
    {
      title: "Beef Protein",
      href: "https://www.muscleandstrength.com/store/category/protein/beef-protein.html",
      products: [
        "/store/stryve-biltong-stick.html",
        "/store/carnivor-mass.html",
        "/store/carnivor.html",
        "/store/carnivor.html",
        "/store/big-steer-1250.html",
        "/store/carnivor.html",
        "/store/stryve-biltong.html",
        "/store/carnivor.html",
        "/store/carnivor-mass.html",
        "/store/vacadillos-carne-seca.html",
        "/store/carnivor.html",
        "/store/carnivor-lean-meal.html",
        "/store/carnivor-coffee.html",
        "/store/stryve-biltong-stick.html",
        "/store/carnivor-coffee.html",
        "/store/beef-biltong.html",
        "/store/beef-biltong.html",
      ],
    },
  ],
};
